# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2bbd0eec6cd6782d373d77fd3eb34c509aacf2d51c182c66059bfe18151ee2fd1cb1cd37528312e462fdb8916e25d03c46fcbae6872e1a720635bc29559b5997

test:
  secret_key_base: c82720ef97fad491692f0bc78d7489dda335d3182410a669299bd6b5e7de091cc2f5c970a7475e01ea7c408dcabf317273a6fd8cacf289280a1b214dab74a2bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
